# Github project: https://github.com/apollographql/spacex
# Explorer: https://studio.apollographql.com/public/spacex-l4uc6p/variant/main/explorer
schema: schema.graphqls
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://main--spacex-l4uc6p.apollographos.net/graphql
      headers:
        user-agent: JS GraphQL
      introspect: false
