@file:Suppress("unused", "MemberVisibilityCanBePrivate", "SpellCheckingInspection")

object AppVersion {
    private const val MAJOR = 0
    private const val MINOR = 0
    private const val BUILD = 5

    const val NAME: String = "${MAJOR}.${MINOR}.${BUILD}"
    val CODE = "${MAJOR}${MINOR.format()}${BUILD.format()}".toInt()

    private fun Int.format() = "%03d".format(this)
}

object AppConfig {
    const val APPLICATION_ID = "com.alxnophis.jetpack"
    const val APP_PACKAGE_NAME = APPLICATION_ID
    const val APP_PACKAGE_NAME_DEBUG = "$APPLICATION_ID.debug"
    const val COMPILE_SDK_VERSION = 33
    const val BUILD_TOOLS_VERSION = "33.0.0"
    const val MIN_SDK_VERSION = 26
    const val TARGET_SDK_VERSION = 33
}

object Modules {
    // App modules
    const val APP = ":app"
    // Shared modules
    const val SHARED_API = ":shared:api"
    const val SHARED_CORE = ":shared:core"
    const val SHARED_KOTLIN = ":shared:kotlin"
    const val SHARED_ROUTER = ":shared:router"
    const val SHARED_TESTING = ":shared:testing"
    // Feature modules
    const val FEATURE_HOME = ":feature:home"
    const val FEATURE_AUTHENTICATION = ":feature:authentication"
    const val FEATURE_GAME_BALL_CLICKER = ":feature:game:ballclicker"
    const val FEATURE_NOTIFICATIONS = ":feature:notifications"
    const val FEATURE_LOCATION_TRACKER =":feature:location-tracker"
    const val FEATURE_POSTS = ":feature:posts"
    const val FEATURE_ROOT = ":feature:root"
    const val FEATURE_SETTINGS = ":feature:settings"
    const val FEATURE_SPACEX = ":feature:spacex"
}

private object Version {
    const val ANDROIDX_ANNOTATIONS = "1.4.0"
    const val ANDROIDX_ACTIVITY = "1.5.0"
    const val ANDROIDX_APPCOMPAT = "1.5.1"
    const val ANDROIDX_ARCH_CORE_COMMON = "2.1.0"
    const val ANDROIDX_ARCH_CORE_RUNTIME = "2.1.0"
    const val ANDROIDX_COMPOSE = "1.2.1"
    const val ANDROIDX_COMPOSE_COMPILER = "1.2.0"
    const val ANDROIDX_COMPOSE_CONSTRAINT_LAYOUT = "1.0.1"
    const val ANDROIDX_COMPOSE_NAVIGATION = "2.5.2"
    const val ANDROIDX_CORE_KTX = "1.8.0"
    const val ANDROIDX_LIFECYCLE = "2.5.1"
    const val ANDROIDX_LIFECYCLE_EXTENSIONS = "2.2.0"
    const val ANDROIDX_TEST_ARCH_CORE = "2.1.0"
    const val ANDROIDX_TEST_JUNIT = "1.1.3"
    const val ANDROIDX_TEST_RULES = "1.4.0"
    const val ANDROIDX_TEST_RUNNER = "1.3.0"
    const val ANDROIDX_VECTOR_DRAWABLE = "1.0.1"
    const val ANDROIDX_WORK = "2.7.1"
    const val APOLLO = "3.4.0"
    const val ARROW = "1.1.3"
    const val ARROW_META = "1.6.0"
    const val COIL = "2.1.0"
    const val GOOGLE_ANDROID_MATERIAL = "1.4.0"
    const val GOOGLE_PLAY_SERVICES_LOCATION = "18.0.0"
    const val GOOGLE_ACCOMPANITS = "0.25.1"
    const val JUNIT = "4.13.2"
    const val JUNIT_JUPITER = "5.8.2"
    const val KOTLIN = "1.7.0"
    const val KOTLIN_COROUTINES = "1.6.4"
    const val KOTLINX_SERIALIZATION_JSON = "1.3.2"
    const val KOIN = "3.1.6"
    const val MOSHI = "1.12.0"
    const val MOCKITO = "4.0.0"
    const val NETWORK_RESPONSE_ADAPTER = "5.0.0"
    const val LEAK_CANARY = "2.9.1"
    const val OKHTTP = "4.10.0"
    const val PERMISSION_DISPATCHER = "4.9.1"
    const val RETROFIT = "2.9.0"
    const val TIMBER = "5.0.1"
    const val TURBINE = "0.11.0"
}

object Dep {
    const val ANDROIDX_ANNOTATIONS = "androidx.annotation:annotation:${Version.ANDROIDX_ANNOTATIONS}"
    const val ANDROIDX_APPCOMPAT = "androidx.appcompat:appcompat:${Version.ANDROIDX_APPCOMPAT}"
    const val ANDROIDX_ACTIVITY = "androidx.activity:activity-ktx:${Version.ANDROIDX_ACTIVITY}"
    const val ANDROIDX_ARCH_CORE_COMMON = "androidx.arch.core:core-common:${Version.ANDROIDX_ARCH_CORE_COMMON}"
    const val ANDROIDX_ARCH_CORE_RUNTIME = "androidx.arch.core:core-runtime:${Version.ANDROIDX_ARCH_CORE_RUNTIME}"
    const val ANDROIDX_ARCH_CORE_TESTING = "androidx.arch.core:core-testing:${Version.ANDROIDX_TEST_ARCH_CORE}"
    const val ANDROIDX_CORE_KTX = "androidx.core:core-ktx:${Version.ANDROIDX_CORE_KTX}"
    const val ANDROIDX_COMPOSE_ACTIVITY = "androidx.activity:activity-compose:${Version.ANDROIDX_ACTIVITY}"
    const val ANDROIDX_COMPOSE_ANIMATION = "androidx.compose.animation:animation:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout-compose:${Version.ANDROIDX_COMPOSE_CONSTRAINT_LAYOUT}"
    const val ANDROIDX_COMPOSE_FOUNDATION = "androidx.compose.foundation:foundation:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_FOUNDATION_LAYOUT = "androidx.compose.foundation:foundation-layout:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_MATERIAL = "androidx.compose.material:material:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_MATERIAL_ICONS_CORE = "androidx.compose.material:material-icons-core:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_MATERIAL_ICONS_EXTENDED = "androidx.compose.material:material-icons-extended:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_NAVIGATION = "androidx.navigation:navigation-compose:${Version.ANDROIDX_COMPOSE_NAVIGATION}"
    const val ANDROIDX_COMPOSE_RUNTIME = "androidx.compose.runtime:runtime:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_UI = "androidx.compose.ui:ui:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_UI_UTIL = "androidx.compose.ui:ui-util:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_UI_TEST = "androidx.compose.ui:ui-test-junit4:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_UI_TEST_MANIFEST = "androidx.compose.ui:ui-test-manifest:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_UI_TOOLING = "androidx.compose.ui:ui-tooling:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_UI_TOOLING_PREVIEW = "androidx.compose.ui:ui-tooling-preview:${Version.ANDROIDX_COMPOSE}"
    const val ANDROIDX_COMPOSE_VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-compose:${Version.ANDROIDX_LIFECYCLE}"
    const val GOOGLE_ACCOMPANITS_SWIPEREFRESH = "com.google.accompanist:accompanist-swiperefresh:${Version.GOOGLE_ACCOMPANITS}"
    const val GOOGLE_ACCOMPANITS_PERMISSIONS = "com.google.accompanist:accompanist-permissions:${Version.GOOGLE_ACCOMPANITS}"
    const val GOOGLE_ACCOMPANITS_PLACEHOLDER = "com.google.accompanist:accompanist-placeholder-material:${Version.GOOGLE_ACCOMPANITS}"
    const val ANDROIDX_LIFECYCLE_COMMON = "androidx.lifecycle:lifecycle-common-java8:${Version.ANDROIDX_LIFECYCLE}"
    const val ANDROIDX_LIFECYCLE_COMPILER = "androidx.lifecycle:lifecycle-compiler:${Version.ANDROIDX_LIFECYCLE}"
    const val ANDROIDX_LIFECYCLE_EXTENSION = "androidx.lifecycle:lifecycle-extensions:${Version.ANDROIDX_LIFECYCLE_EXTENSIONS}"
    const val ANDROIDX_LIFECYCLE_RUNTIME = "androidx.lifecycle:lifecycle-runtime-ktx:${Version.ANDROIDX_LIFECYCLE}"
    const val ANDROIDX_LIFECYCLE_VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Version.ANDROIDX_LIFECYCLE}"
    const val ANDROIDX_TEST_JUNIT = "androidx.test.ext:junit-ktx:${Version.ANDROIDX_TEST_JUNIT}"
    const val ANDROIDX_TEST_RUNNER = "androidx.test:runner:${Version.ANDROIDX_TEST_RUNNER}"
    const val ANDROIDX_TEST_RULES = "androidx.test:rules:${Version.ANDROIDX_TEST_RULES}"
    const val ANDROIDX_VECTOR_DRAWABLE = "androidx.vectordrawable:vectordrawable:${Version.ANDROIDX_VECTOR_DRAWABLE}"
    const val ANDROIDX_WORK = "androidx.work:work-runtime-ktx:${Version.ANDROIDX_WORK}"
    const val APOLLO_API = "com.apollographql.apollo3:apollo-api:${Version.APOLLO}"
    const val APOLLO_ADAPTERS = "com.apollographql.apollo3:apollo-adapters:${Version.APOLLO}"
    const val APOLLO_NORMALIZED_CACHE = "com.apollographql.apollo3:apollo-normalized-cache:${Version.APOLLO}"
    const val APOLLO_NORMALIZED_CACHE_SQLITE = "com.apollographql.apollo3:apollo-normalized-cache-sqlite:${Version.APOLLO}"
    const val APOLLO_RUNTIME = "com.apollographql.apollo3:apollo-runtime:${Version.APOLLO}"
    const val APOLLO_TESTING_SUPPORT = "com.apollographql.apollo3:apollo-testing-support:${Version.APOLLO}"
    const val ARROW_STACK = "io.arrow-kt:arrow-stack:${Version.ARROW}"
    const val ARROW_CORE = "io.arrow-kt:arrow-core"
    const val ARROW_FX_COROUTINES = "io.arrow-kt:arrow-fx-coroutines"
    const val ARROR_META = "io.arrow-kt:arrow-meta:${Version.ARROW_META}"
    const val COIL = "io.coil-kt:coil-compose:${Version.COIL}"
    const val COROUTINES_CORE = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Version.KOTLIN_COROUTINES}"
    const val COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Version.KOTLIN_COROUTINES}"
    const val COROUTINES_TEST = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Version.KOTLIN_COROUTINES}"
    const val GOOGLE_ANDROID_MATERIAL = "com.google.android.material:material:${Version.GOOGLE_ANDROID_MATERIAL}"
    const val GOOGLE_PLAY_SERVICES_LOCATION = "com.google.android.gms:play-services-location:${Version.GOOGLE_PLAY_SERVICES_LOCATION}"
    const val JUNIT = "junit:junit:${Version.JUNIT}"
    const val JUNIT_VINTAGE_ENGINE = "org.junit.vintage:junit-vintage-engine:${Version.JUNIT_JUPITER}"
    const val JUNIT_JUPITER_API = "org.junit.jupiter:junit-jupiter-api:${Version.JUNIT_JUPITER}"
    const val JUNIT_JUPITER_ENGINE = "org.junit.jupiter:junit-jupiter-engine:${Version.JUNIT_JUPITER}"
    const val JUNIT_JUPITER_PARAMS = "org.junit.jupiter:junit-jupiter-params:${Version.JUNIT_JUPITER}"
    const val KOTLINX_SERIALIZATION_JSON = "org.jetbrains.kotlinx:kotlinx-serialization-json:${Version.KOTLINX_SERIALIZATION_JSON}"
    const val KOIN_ANDROID = "io.insert-koin:koin-android:${Version.KOIN}"
    const val KOIN_ANDROID_COMPOSE = "io.insert-koin:koin-androidx-compose:${Version.KOIN}"
    const val KOIN_ANDROID_WORK_MANAGER = "io.insert-koin:koin-androidx-workmanager:${Version.KOIN}"
    const val KOIN_TEST = "io.insert-koin:koin-test:${Version.KOIN}"
    const val MOCKITO = "org.mockito:mockito-junit-jupiter:${Version.MOCKITO}"
    const val MOCKITO_ANDROID = "org.mockito:mockito-android:${Version.MOCKITO}"
    const val MOCKITO_INLINE = "org.mockito:mockito-inline:${Version.MOCKITO}"
    const val MOCKITO_KOTLIN = "org.mockito.kotlin:mockito-kotlin:${Version.MOCKITO}"
    const val MOSHI = "com.squareup.moshi:moshi-kotlin:${Version.MOSHI}"
    const val MOSHI_ADAPTER = "com.squareup.moshi:moshi-adapters:${Version.MOSHI}"
    const val MOSHI_KOTLIN_CODEGEN = "com.squareup.moshi:moshi-kotlin-codegen:${Version.MOSHI}"
    const val NETWORK_RESPONSE_ADAPTER = "com.github.haroldadmin:NetworkResponseAdapter:${Version.NETWORK_RESPONSE_ADAPTER}"
    const val LEAK_CANARY = "com.squareup.leakcanary:leakcanary-android:${Version.LEAK_CANARY}"
    const val PERMISSION_DISPATCHER = "com.github.permissions-dispatcher:permissionsdispatcher:${Version.PERMISSION_DISPATCHER}"
    const val PERMISSION_DISPATCHER_PROCESSOR = "com.github.permissions-dispatcher:permissionsdispatcher-processor:${Version.PERMISSION_DISPATCHER}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${Version.RETROFIT}"
    const val RETROFIT_CONVERTER_MOSHI = "com.squareup.retrofit2:converter-moshi:${Version.RETROFIT}"
    const val OKHTTP = "com.squareup.okhttp3:okhttp:${Version.OKHTTP}"
    const val OKHTTP_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor:${Version.OKHTTP}"
    const val TURBINE = "app.cash.turbine:turbine:${Version.TURBINE}"
    const val TIMBER = "com.jakewharton.timber:timber:${Version.TIMBER}"
}
