name: Android CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check Ktlint
        run: ./gradlew ktlintCheck
      - name: Debug Unit tests
        run: ./gradlew testDebugUnitTest
      - name: Assemble Release
        run: ./gradlew assembleRelease
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ALX_STORE_FILE }}
          alias: ${{ secrets.ALX_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ALX_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ALX_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "31.0.0"
      # Example use of `signedReleaseFile` output -- not needed
      - name: Upload Release APK
        uses: actions/upload-artifact@v2
        with:
          name: CaelumSignedApp
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
