name: Android CI

on:
  push:
    branches: [ develop, main ]
  pull_request:

permissions:
  actions: write
  contents: read
  security-events: write

jobs:

  check_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Workflow Runs
        uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Setup JDK Zulu 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check Ktlint
        run: ./gradlew ktlintCheck

      - name: Debug Unit tests
        run: ./gradlew koverHtmlReportDebug
